
FROM alpine:3

LABEL author="Arthur Hozana Arthur"
LABEL company="Arthur Hozana" website="https://github.com/arthurhzna"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"